export const posts = [
  { id: 1, title: 'Post 1', summary: 'Summary for Post 1...' },
  { id: 2, title: 'Post 2', summary: 'Summary for Post 2...' },
  { id: 3, title: 'Post 3', summary: 'Summary for Post 3...' },
];

import { img1, img2, img3 } from "./assets";

export const productCard = [
  {
    id: 1,
    img: img1,
    title: 'Rent',
    name: "Blue View Real Estate",
    price: "2,600",
    beds: '2',
    baths: '2',
    sqft: '1200',
    location: '21 Forest Hill Drive',
    button: 'View',
    buttonColor: "bg-blue-700",
  },
  {
    id: 2,
    img: img2,
    title: 'Rent',
    name: "Blue View Real Estate",
    price: "2,600",
    beds: '2',
    baths: '2',
    sqft: '1200',
    location: '21 Forest Hill Drive',
    button: 'View',
    buttonColor: "bg-blue-700",
  },
  {
    id: 3,
    img: img3,
    title: 'Rent',
    name: "Blue View Real Estate",
    price: "2,600",
    beds: '2',
    baths: '2',
    sqft: '1200',
    location: '21 Forest Hill Drive',
    button: 'View',
    buttonColor: "bg-blue-700",
  },
];

export const productDetails = [
  {
    id: 1,
    img: img1,
    title: 'Rent',
    name: "Blue View Real Estate",
    price: "2,600",
    beds: '2',
    baths: '2',
    sqft: '1200',
    location: '21 Forest Hill Drive',
    button: 'view',
    buttonColor: "bg-blue-700",
  },
  {
    id: 2,
    img: img2,
    title: 'Rent',
    name: "Blue View Real Estate",
    price: "2,600",
    beds: '2',
    baths: '2',
    sqft: '1200',
    location: '21 Forest Hill Drive',
    button: 'view',
    buttonColor: "bg-blue-700",
  },
  {
    id: 3,
    img: img3,
    title: 'Rent',
    name: "Blue View Real Estate",
    price: "2,600",
    beds: '2',
    baths: '2',
    sqft: '1200',
    location: '21 Forest Hill Drive',
    button: 'view',
    buttonColor: "bg-blue-700",
  },
]